### ISSUE TITLE
Command execution style

### ISSUE THREAD

**Issue by alpha0010** [tomolt/GitBlocks#1]
You can eliminate much of the platform specific code by dropping the `cmd.exe /C` and `xterm -e` prefix from most commands (since they are only needed if you are trying to use built in shell features, such as environment variables and embedded commands), and use [wxRmdir()](http://docs.wxwidgets.org/3.0/group__group__funcmacro__file.html#ga9ae2276737ad4fe72ea96c5f2d9bbfd3) to delete.

Also, when giving a command string, `_("xyz")` means that the text will be run through translation.  Good for menus and dialogues; bad for console commands.  Use `wxT("xyz")` for command literals.

**Comment by tomolt** [comment]
I used xterm and cmd only for push, pull and fetch, mainly because they interact with the user (gather password etc.). I already knew that one of the two functions _() and _T() also translates the input text, but I somehow confused them.
